add option to allow dashes in external links
hubzero/hubzero-cms pull request #1619
Opened 2023-05-07 16:49 UTC by JackS9

### Original support ticket: 
- [QUBES #4821](https://qubeshub.org/support/ticket/4821)
### JIRA tasks: 
- [QUBES-29](https://sdx-sdsc.atlassian.net/browse/QUBES-29)
- [QUBES-35](https://sdx-sdsc.atlassian.net/browse/QUBES-35)
### Brief summary of issue:
Embedded HTML code for a Twitter timeline feed was having some of the HREF attributes, such as limit on number of posts, stripped before being processes. This was regardless of whether using the page macro, the mod_twitterfeed module, or hand-coding the embedded HTML.
### Brief summary of fix/changes:
Many potential avenues were explored, including the Sanitizer (HTMLPurifier), but it turned out to be the 'Content - External Links' plugin (plugins/content/externalhref) responding to a onContentPrepare event (trigger) that was parsing (tokenizing) attributes and treating dashes as separators. The fix was to modify the regex pattern to allow dashes in attributes (and not break them up). A plugin configuration option was also added to enable/disable this feature (allowing dashes in attributes for external links).
### Brief summary of testing:
The undesired behavior was replicated on both the QUBES production site (on a WebDev group page) and on my personal dev (AWS) machine and the externalhref fix above resolved the issue.
### Hot fix required?  No.
Fortunately, there is a workaround for this issue, by adding ‘twitter-timeline’ to the list of classes in the ‘Content - External Links’ plugin to exclude it from being processed. This was shared with the client and implemented on the QUBES production site.

2023-07-26 18:01 UTC, nkissebe commented
I'd like to know more about the original issue and what this plugin is supposed to do as I am actually not really familiar with it. Lets have a quick zoom call and resolve this.

2023-08-23 18:11 UTC, dbenham requested changes

2023-08-23 18:11 UTC, dbenham commented on core/plugins/content/externalhref/externalhref.php
> +				if ($allow_dashes)
go ahead and remove the option per our group meeting discussion

2023-10-06 01:28 UTC, nkissebe commented
Closing this PR, I merged a standalone commit with the pattern change without the conditional or config option as the change appears to be universally correct for modern usage. fa235692bf7d8207912bc61f27ff91b20f407451

2023-10-06 01:28 UTC, closed without merging